const { test, expect } = require('@playwright/test');

test('Next.js → Express: login, troca de senha, emissão, PDF, validação e logout', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/dashboard');
  await expect(page).toHaveURL(/\/login$/);
  await page.getByLabel('Usuário', { exact: true }).fill('e2e_admin');
  await page.getByLabel('Senha', { exact: true }).fill('SenhaInicialE2E123!');
  await page.getByRole('button', { name: 'Entrar no sistema' }).click();
  await expect(page).toHaveURL(/\/configuracoes$/);
  await page.getByLabel('Senha atual', { exact: true }).fill('SenhaInicialE2E123!');
  await page.getByLabel('Nova senha', { exact: true }).fill('SenhaNovaE2ESegura123!');
  await page.getByLabel('Confirmar nova senha', { exact: true }).fill('SenhaNovaE2ESegura123!');
  await page.getByRole('button', { name: 'Alterar senha' }).click();
  await expect(page.locator('p[role="alert"]')).toHaveText('Senha alterada com sucesso.');
  await page.getByRole('link', { name: 'Novo certificado', exact: true }).click();
  await page.getByLabel('Nome completo').fill('Aluno de Hospedagem');
  await page.getByLabel('Data de início').fill('2026-01-10');
  await page.getByLabel('Data de término').fill('2026-07-10');
  await page.getByRole('button', { name: 'Emitir certificado' }).click();
  await expect(page.getByRole('heading', { name: 'Certificado criado com sucesso' })).toBeVisible();
  const code = await page.locator('p.code').textContent();
  const pdfPath = await page.getByRole('link', { name: 'Baixar PDF' }).getAttribute('href');
  const pdf = await page.request.get(pdfPath);
  expect(pdf.status()).toBe(200);
  expect((await pdf.body()).subarray(0, 4).toString()).toBe('%PDF');
  await page.goto('/dashboard');
  await expect(page.getByText('Aluno de Hospedagem', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Editar', exact: true }).click();
  await page.getByLabel('Nome completo').fill('Aluno Editado');
  await page.getByRole('button', { name: 'Salvar alterações' }).click();
  await expect(page.getByText('Aluno Editado', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Sair', exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
  expect((await page.request.get('/api/me')).status()).toBe(401);
  await page.goto(`/validar/${code}`);
  await expect(page.getByRole('heading', { name: 'Certificado válido', exact: true })).toBeVisible();
  await expect(page.getByText('Aluno Editado', { exact: true })).toBeVisible();
  await page.goto('/validar/codigo-inexistente');
  await expect(page.locator('p[role="alert"]')).toHaveText('Certificado não encontrado.');
  expect(errors).toEqual([]);
});
